name: On Push

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Push event happened
        run: |
          echo "Push event happened!"
          echo "Pushed by: ${{ github.actor }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
